services:
  backend:
    image: ghcr.io/mangal2305/todo-backend:latest
    container_name: todo-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
  frontend:
    image: ghcr.io/mangal2305/todo-frontend:latest
    container_name: todo-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8000:80"